name: Benchmark Master

on:
  push:
    branches:
      - master

permissions:
  # deployments permission to deploy GitHub pages website
  deployments: write
  # contents permission to update benchmark contents in gh-pages branch
  contents: write

jobs:
  benchmark:
    runs-on: ubuntu-latest
    outputs:
      results: ${{ steps.benchmark.outputs.results }}

    steps:
      - uses: actions/checkout@v2
        with:
          path: "./yew"

      # - uses: ./yew/.github/workflows/benchmark-run
      #   id: benchmark

  store:
    runs-on: ubuntu-latest
    needs: benchmark

    steps:
      - uses: actions/checkout@v2

      - name: Store latest benchmark data for Pr checking
        uses: actions/cache@v1
        with:
          path: ./cache
          key: ${{ runner.os }}-benchmark-data

      # - run: |
      #     touch results.json
      #     echo '${{ needs.benchmark.outputs.results }}' >> results.json

      - run: |
          touch results.json
          echo '[{"name":"yew-struct-keyed 01_run1k","unit":"","value":"388.8375"},{"name":"yew-struct-keyed 02_replace1k","unit":"","value":"197.188"},{"name":"yew-struct-keyed 03_update10th1k_x16","unit":"","value":"365.044"},{"name":"yew-struct-keyed 04_select1k","unit":"","value":"77.749"},{"name":"yew-struct-keyed 05_swap1k","unit":"","value":"98.0205"},{"name":"yew-struct-keyed 06_remove-one-1k","unit":"","value":"31.800000000000004"},{"name":"yew-struct-keyed 07_create10k","unit":"","value":"2057.484"},{"name":"yew-struct-keyed 08_create1k-after1k_x2","unit":"","value":"414.841"},{"name":"yew-struct-keyed 09_clear1k_x8","unit":"","value":"181.2515"},{"name":"yew-struct-keyed 21_ready-memory","unit":"","value":"0.9196929931640624"},{"name":"yew-struct-keyed 22_run-memory","unit":"","value":"1.4311790466308594"},{"name":"yew-struct-keyed 23_update5-memory","unit":"","value":"1.4167861938476562"},{"name":"yew-struct-keyed 24_run5-memory","unit":"","value":"1.4776687622070312"},{"name":"yew-struct-keyed 25_run-clear-memory","unit":"","value":"1.0857925415039062"},{"name":"yew-struct-keyed 31_startup-ci","unit":"","value":"1730.8239999999998"},{"name":"yew-struct-keyed 32_startup-bt","unit":"","value":"36.36799999999999"},{"name":"yew-struct-keyed 34_startup-totalbytes","unit":"","value":"363.7998046875"}]' >> results.json

      # gh-pages branch is updated and pushed automatically with extracted benchmark data
      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: "Yew master branch benchmarks by commits (Lower is better)"
          tool: "customSmallerIsBetter"
          output-file-path: results.json
          gh-pages-branch: "gh-pages"
          # Access token to deploy GitHub Pages branch
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # Push and deploy GitHub pages branch automatically
          auto-push: true

      - name: Store benchmark data
        run: |
          cd ./cache
          mv -f ../results.json results.json
