name: Benchmark

on:
  push:
    branches:
      - master
  pull_request_target:

permissions:
  # deployments permission to deploy GitHub pages website
  deployments: write
  # contents permission to aa update benchmark contents in gh-pages branch
  contents: write

jobs:
  results:
    runs-on: ubuntu-latest

    steps:
      - run: echo hi
