name: Benchmark

on:
  push:
    branches:
      - master
  pull_request_target:

permissions:
  # deployments permission to deploy GitHub pages website
  deployments: write
  # contents permission to update benchmark contents in gh-pages branch
  contents: write

jobs:
  results:
    runs-on: ubuntu-latest

    steps:
      - run: echo "${{ github.event.pull_request }}"
      - run: echo "${{ github.event.pull_request.labels }}"
      - run: echo "${{ contains(github.event.pull_request.labels.*.name, 'performance') }}"
      - run: echo "${{ contains(github.event.pull_request.labels.*.name, 'performance') }}"
      - run: echo "${{ contains(github.event.pull_request_target.labels.*.name, 'performance') }}"
