name: Benchmark Master

on:
  push:
    branches:
      - master

permissions:
  # deployments permission to deploy GitHub pages website
  deployments: write
  # contents permission to update benchmark contents in gh-pages branch
  contents: write

jobs:
  benchmark:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          path: "./yew"

      - uses: ./yew/.github/workflows/benchmark-run
        id: benchmark

      - run: |
          cd yew
          touch results.json
          echo ${{ steps.benchmark.outputs.results }} >> results.json

      # gh-pages branch is updated and pushed automatically with extracted benchmark data
      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          working-directory: ./yew
          name: "Yew master branch benchmarks by commits"
          tool: "customSmallerIsBetter"
          output-file-path: results.json
          gh-pages-branch: "gh-pages"
          # Access token to deploy GitHub Pages branch
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # Push and deploy GitHub pages branch automatically
          auto-push: true
