name: Benchmarkee

on:
  workflow_dispatch:
    inputs:
      app:
        description: "app to benchmark"
        required: true
        type: choice
        options:
          - yew_app_for_benchmark
          #TODO: - yew_hooks_app_for_benchmark

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          path: "./benchmark-target-source"

      - uses: actions/checkout@v2
        with:
          repository: krausest/js-framework-benchmark
          path: "./js-framework-benchmark"

      - uses: actions/checkout@v2
        with:
          #repository: yewstack/yew
          path: "./benchmark-baseline-source"

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true
          profile: minimal

      - uses: jetli/trunk-action@v0.1.0
        with:
          version: "latest"

      - name: save yew setup
        run: |
          mkdir yew-setup
          cp -r js-framework-benchmark/frameworks/keyed/yew/* yew-setup/
          cd yew-setup/bundled-dist
        #  rm -rf ./*

      - name: replace framework version
        run: |
          replace="  \"frameworkVersion\": \"\""
          input=$(cat yew-setup/package.json)
          output=$(echo "$input" | sed -e "s@\"frameworkVersion\": .*\"@$replace@g")
          if [[ "$input" == "$output" ]]; then
            echo "ERROR: failed to configure framework version"
            exit 1
          fi
          echo "$output" > yew-setup/package.json
          echo "$output"

      - name: delete all keyed frameworks
        run: |
          cd js-framework-benchmark/frameworks/keyed
          rm -rf ./*

      - name: delete all non-keyed frameworks
        run: |
          cd js-framework-benchmark/frameworks/non-keyed
          rm -rf ./*

      - name: create baseline and target framework folders
        run: |
          cd js-framework-benchmark/frameworks/keyed
          mkdir baseline
          mkdir target

      - name: copy necessary framework files
        run: |
          cp -r yew-setup/* js-framework-benchmark/frameworks/keyed/baseline/
          cp -r yew-setup/* js-framework-benchmark/frameworks/keyed/target/

      # - name: build benchmark baseline app
      #   run: |
      #     cd benchmark-baseline-source/examples/${{ github.event.inputs.app }}
      #     trunk build --release --public-url "/frameworks/keyed/yew"

      # - name: build benchmark target app
      #   run: |
      #     cd benchmark-target-source/examples/${{ github.event.inputs.app }}
      #     trunk build --release --public-url "/frameworks/keyed/yew"

      # - name: move dist files
      #   run: |
      #     mv benchmark-baseline-source/examples/${{ github.event.inputs.app }}/dist/* js-framework-benchmark/frameworks/keyed/baseline/bundled-dist/
      #     mv benchmark-target-source/examples/${{ github.event.inputs.app }}/dist/* js-framework-benchmark/frameworks/keyed/target/bundled-dist/

      ## chromedriver  fix

      # - name: Setup ChromeDriver
      #   uses: nanasess/setup-chromedriver@master

      # - name: remove chromedriver
      #   run: |
      #     cd js-framework-benchmark/webdriver-ts/src
      #     replace="\/\/Do nothing in this line"

      #     input=$(cat forkedBenchmarkRunnerWebdriver.ts)
      #     output=$(echo "$input" | sed -e "s@.*require(\"chromedriver\");@$replace@g")
      #     if [[ "$input" == "$output" ]]; then
      #       echo "ERROR: failed to remove use of chromedriver npm package"
      #       exit 1
      #     fi
      #     echo "$output" > forkedBenchmarkRunnerWebdriver.ts
      #     echo "$output"

      #     input=$(cat isKeyed.ts)
      #     output=$(echo "$input" | sed -e "s@.*require(\"chromedriver\");@$replace@g")
      #     if [[ "$input" == "$output" ]]; then
      #       echo "ERROR: failed to remove use of chromedriver npm package"
      #       exit 1
      #     fi
      #     echo "$output" > isKeyed.ts
      #     echo "$output"

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: js-framework-benchmark npm ci
        run: |
          cd js-framework-benchmark
          npm ci

      - name: js-framework-benchmark npm start
        run: |
          cd js-framework-benchmark
          npm start &

      - name: js-framework-benchmark/webdriver-ts npm ci
        run: |
          cd js-framework-benchmark/webdriver-ts
          npm ci
          npm install chromedriver --chromedriver-force-download

      - name: js-framework-benchmark/webdriver-ts npm run compile
        run: |
          cd js-framework-benchmark/webdriver-ts
          npm run compile

      - name: js-framework-benchmark npm run build-prod
        run: |
          cd js-framework-benchmark
          npm run build-prod

      - name: js-framework-benchmark/webdriver-ts npm run bench
        run: |
          cd js-framework-benchmark/webdriver-ts
          npm run bench -- --headless

      - name: display results
        run: |
          cd js-framework-benchmark/webdriver-ts/results
          ls -la
          echo ==================
          cat baseline-keyed_01_run1k.json
          cat target-keyed_01_run1k.json
          echo ==================
          cat baseline-keyed_02_replace1k.json
          cat target-keyed_02_replace1k.json
          echo ==================
          cat baseline-keyed_03_update10th1k_x16.json
          cat target-keyed_03_update10th1k_x16.json
          echo ==================
          cat baseline-keyed_04_select1k.json
          cat target-keyed_04_select1k.json
          echo ==================
          cat baseline-keyed_05_swap1k.json
          cat target-keyed_05_swap1k.json
          echo ==================
          cat baseline-keyed_06_remove-one-1k.json
          cat target-keyed_06_remove-one-1k.json
          echo ==================
          cat baseline-keyed_07_create10k.json
          cat target-keyed_07_create10k.json
          echo ==================
          cat baseline-keyed_08_create1k-after1k_x2.json
          cat target-keyed_08_create1k-after1k_x2.json
          echo ==================
          cat baseline-keyed_09_clear1k_x8.json
          cat target-keyed_09_clear1k_x8.json
          echo ==================
          cat baseline-keyed_21_ready-memory.json
          cat target-keyed_21_ready-memory.json
          echo ==================
          cat baseline-keyed_22_run-memory.json
          cat target-keyed_22_run-memory.json
          echo ==================
          cat baseline-keyed_23_update5-memory.json
          cat target-keyed_23_update5-memory.json
          echo ==================
          cat baseline-keyed_24_run5-memory.json
          cat target-keyed_24_run5-memory.json
          echo ==================
          cat baseline-keyed_25_run-clear-memory.json
          cat target-keyed_25_run-clear-memory.json
          echo ==================
          cat baseline-keyed_31_startup-ci.json
          cat target-keyed_31_startup-ci.json
          echo ==================
          cat baseline-keyed_32_startup-bt.json
          cat target-keyed_32_startup-bt.json
          echo ==================
          cat baseline-keyed_34_startup-totalbytes.json
          cat target-keyed_34_startup-totalbytes.json
